-- 서울에 위치한 식당 목록 출력하기 level 4
-- REST_INFO 식당정보
-- REST_REVIEW 리뷰정보
-- 서울에 위치한 식당
SELECT REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_INFO
JOIN REST_REVIEW USING (REST_ID)
WHERE ADDRESS LIKE "서울%"
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC;