-- 조건에 부합하는 중고거래 댓글 조회하기
SELECT ugb.TITLE, ugb.BOARD_ID,	ugr.REPLY_ID, ugr.WRITER_ID, ugr.CONTENTS, ugr.CREATED_DATE
FROM USED_GOODS_BOARD ugb
JOIN USED_GOODS_REPLY ugr ON ugb.BOARD_ID = ugr.BOARD_ID
WHERE YEAR(ugb.CREATED_DATE) = 2022 AND MONTH(ugb.CREATED_DATE) = 10
ORDER BY ugr.CREATED_DATE ASC, ugb.TITLE ASC;